### ISSUE TITLE
右上の検索が動いてない

### ISSUE THREAD

**Issue by mehm8128** [traPtitech/traPortfolio-Dashboard#170]
router.pushしてるけど対応するページがないのが原因っぽそう
多分UIの方を参考にできるはず: https://github.com/traPtitech/traPortfolio-UI/blob/master/src/pages/SearchPage.vue

**Comment by Pugma** [comment]
setupのところは反映されているのは確認済みなので、検索後のページを作ります
ただ、UIとは`contests/menberlist``PageTitle`など一部対応するコンポーネントがない場合があるのでそこから作ることになりそうです

**Comment by mehm8128** [comment]
他のページのデザインに寄せる感じで先にFigmaでデザイン作るともしかしたらやりやすいかもです(おまかせするけど)

**Comment by Pugma** [comment]
とりあえずドキュメント代わりにFigma作ろうかと考えています！

**Comment by Pugma** [comment]
このページ、とりあえず枠自体は作ったんですけど、検索したあとに何を表示したいかがあまり明確じゃないかもです
外部向けページではメンバーを検索できるようになっていますが、それは内部向けでは必要なさそうですし… (外部向けページもユーザーしか検索できないのはちょっと非自明なような気もします)

イベントとかコンテストとかの情報を調べられる方がいいんですかね？

**Comment by mehm8128** [comment]
イベントとかコンテストは1回クリックして一覧ページ飛べば検索フォーム別で存在するし、検索いらない気がしてきた...

**Comment by mehm8128** [comment]
まあやるならイベント、コンテスト、コンテストチーム、プロジェクトを全部一括で検索できるようにするって感じかな

**Comment by Pugma** [comment]
そうですね、常に表示されているヘッダーに埋め込まれた検索バーなので、一旦全部を一括で検索できるようにする方針で実装してみます
外部向けページも現状だとユーザー検索しかできないと思いますが、それはどうしますか…？

**Comment by mehm8128** [comment]
外部ページはまた別で考えるということで...(多分同じように色々検索できるように変更するのがいいとは思います)

**Comment by Pugma** [comment]
検索ボックス自体を消すことになったので、一旦消してからPR出します
