### ISSUE TITLE
はみ出てる

### ISSUE THREAD

**Issue by mehm8128** [traPtitech/traPortfolio-Dashboard#181]
どう直せばいいか分からず
![image](https://github.com/traPtitech/traPortfolio-Dashboard/assets/83744975/1451261b-3344-4279-af60-9dac0020cf16)

**Comment by Pugma** [comment]
これは、
「プロジェクト作成」
とボタンのdivを`grid` or `inline-grid`にして`justify-items: center;`
で指定するとか、やってみると中央揃えにできそうです

**Comment by mehm8128** [comment]
ボタンを文字の横幅に合わせるって感じかな
他のページと横幅が統一されてないのがちょっと気になるけど、まあいいか

**Comment by mehm8128** [comment]
そもそも文字入れなくても分かるという説はある

**Comment by mehm8128** [comment]
文字なくていい気がしてきたから消す方向かな(多分「検索」もいらない)
