### ISSUE TITLE
チェックボックスコンポーネントの実装

### ISSUE THREAD

**Issue by toshi-pono** [traPtitech/traPortfolio-Dashboard#19]
チェックボックスの見た目はこれ
https://www.figma.com/file/BVnhB2JyTjKsGKdnAJDksb/traPortfolio?node-id=2237%3A1262

**Comment by tesso57** [comment]
どこにも使ってないので、保留で。

**Comment by mehm8128** [comment]
これ一旦closeしちゃいますね
