### ISSUE TITLE
アカウント一覧で「traP広報にPRを許可する」みたいな表示を消す

### ISSUE THREAD

**Issue by mehm8128** [traPtitech/traPortfolio-Dashboard#328]
トグルを消したのでこれもいらない

**Comment by mehm8128** [comment]
公開ページの方はどうせ変えるのでいいのですが、dashboardは今後UIを大きく変更する予定ないと思うので、できればコードの修正に合わせてFigmaの方も直しておいてほしいです🙏

**Comment by Pugma** [comment]
こちらFigmaは僕が対応しておきます

**Comment by Pugma** [comment]
↑Figmaの変更は対応完了しました
